package pure2rss_test

import (
	"bytes"
	"testing"

	"github.com/matryer/is"

	"github.com/encero/pure2rss/src/pure2rss"
)

var exampeSiteMapListXML =
`
<?xml version="1.0" encoding="UTF-8"?><?xml-stylesheet type="text/xsl" href="//blog.purestorage.com/wp-content/plugins/wordpress-seo/css/main-sitemap.xsl"?>
    <sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
        <sitemap>
            <loc>https://blog.purestorage.com/post-sitemap.xml</loc>
            <lastmod>2024-05-01T19:29:11+00:00</lastmod>
        </sitemap>
        <sitemap>
            <loc>https://blog.purestorage.com/post-sitemap2.xml</loc>
            <lastmod>2024-02-27T18:31:11+00:00</lastmod>
        </sitemap>
    </sitemapindex>
    <!-- XML Sitemap generated by Yoast SEO -->
`

func  TestParseSitemapList(t *testing.T) {
    is := is.New(t)

    buf := bytes.NewBufferString(exampeSiteMapListXML)
    list, err := pure2rss.ParseSiteMapList(buf)
    is.NoErr(err)

    is.Equal(len(list), 2) // parsed sitemap has two items

    first := list[0]
    second := list[1]

    is.Equal(first.Loc, "https://blog.purestorage.com/post-sitemap.xml")
    is.Equal(second.Loc, "https://blog.purestorage.com/post-sitemap2.xml")
}


var exampleSitemapXML = `
<?xml version="1.0" encoding="UTF-8"?><?xml-stylesheet type="text/xsl" href="//blog.purestorage.com/wp-content/plugins/wordpress-seo/css/main-sitemap.xsl"?>
    <urlset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1" xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd http://www.google.com/schemas/sitemap-image/1.1 http://www.google.com/schemas/sitemap-image/1.1/sitemap-image.xsd" xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
        <url>
            <loc>https://blog.purestorage.com/purely-technical/pure-storages-take-on-server-flash-caching/</loc>
            <lastmod>2024-02-16T19:26:25+00:00</lastmod>
            <image:image>
                <image:loc>https://blog.purestorage.com/wp-content/uploads/2012/02/espresso-300x300.jpg</image:loc>
            </image:image>
            <image:image>
                <image:loc>https://blog.purestorage.com/wp-content/uploads/2012/02/Pure_Cappuchino-300x249.jpg</image:loc>
            </image:image>
        </url>
        <url>
            <loc>https://blog.purestorage.com/purely-informational/take-a-picture-itll-last-longer/</loc>
            <lastmod>2024-02-16T19:26:28+00:00</lastmod>
            <image:image>
                <image:loc>https://blog.purestorage.com/wp-content/uploads/2011/04/0c474dfe-a2b1-40e6-bcd2-a67b6cb493a5.jpeg</image:loc>
            </image:image>
        </url>
        <url>
            <loc>https://blog.purestorage.com/purely-technical/deduplication-compression-and-sql-server-databases-part-1/</loc>
            <lastmod>2024-02-16T19:26:31+00:00</lastmod>
        </url>
    </urlset>
`

func TestParseSitemap(t *testing.T) {
    is := is.New(t)

    reader := bytes.NewBufferString(exampleSitemapXML)

    posts, err := pure2rss.ParseSiteMap(reader)
    is.NoErr(err)

    is.Equal(len(posts), 3) // parsed 3 posts from sitemap

    first := posts[0]

    is.Equal(first.Loc, "https://blog.purestorage.com/purely-technical/pure-storages-take-on-server-flash-caching/")
    is.Equal(first.LastMod, "2024-02-16T19:26:25+00:00")
}
