on:
  schedule:
  - cron: "0 17 * * *"
  workflow_dispatch:
jobs:
  update_feed:
    runs-on: ubuntu-latest
    name: Update the rss feed
    steps:
    - uses: actions/checkout@v4
    - name: run the updater
      run: |
        ./pure2rss
    - uses: stefanzweifel/git-auto-commit-action@v5
      with: 
        file_pattern: 'rss.xml posts.json'
